In [48]:
import pandas as pd
import numpy as np

In [49]:
datas = pd.date_range('20190101', periods = 60, freq = 'D')
df = pd.DataFrame(np.random.randn(60,5), index = datas, columns = list('ABCDE'))

In [50]:
df.head(3)

                   A         B         C         D         E
2019-01-01 -0.358184 -0.804749  0.611427  0.545171 -0.922421
2019-01-02  0.065990 -0.721489  0.634475  0.569853  0.287334
2019-01-03  1.870857  0.228576  0.786197 -0.777071  0.482105

In [51]:
df['F'] = df.A[df.A > 0]

In [52]:
df.head(5)

                   A         B         C         D         E         F
2019-01-01 -0.358184 -0.804749  0.611427  0.545171 -0.922421       NaN
2019-01-02  0.065990 -0.721489  0.634475  0.569853  0.287334  0.065990
2019-01-03  1.870857  0.228576  0.786197 -0.777071  0.482105  1.870857
2019-01-04  0.606655 -0.253794 -1.061497 -0.181201 -0.249874  0.606655
2019-01-05 -0.502408 -0.798812  1.210614 -1.788177  0.366809       NaN

In [53]:
df2 = df.copy()

In [54]:
df3 = df.copy()

In [55]:
df2.dropna().shape

(38, 6)

In [56]:
df3.head(3)

                   A         B         C         D         E         F
2019-01-01 -0.358184 -0.804749  0.611427  0.545171 -0.922421       NaN
2019-01-02  0.065990 -0.721489  0.634475  0.569853  0.287334  0.065990
2019-01-03  1.870857  0.228576  0.786197 -0.777071  0.482105  1.870857

In [60]:
df3.F = df3.F.fillna(np.mean(df3.A))

In [61]:
df3.shape

(60, 6)

In [62]:
df3

                   A         B         C         D         E         F
2019-01-01 -0.358184 -0.804749  0.611427  0.545171 -0.922421  0.299659
2019-01-02  0.065990 -0.721489  0.634475  0.569853  0.287334  0.065990
2019-01-03  1.870857  0.228576  0.786197 -0.777071  0.482105  1.870857
2019-01-04  0.606655 -0.253794 -1.061497 -0.181201 -0.249874  0.606655
2019-01-05 -0.502408 -0.798812  1.210614 -1.788177  0.366809  0.299659
2019-01-06  0.197696 -1.308079 -0.325214 -1.873872 -0.486058  0.197696
2019-01-07  0.440276 -0.127049  0.602279  1.203381  0.695060  0.440276
2019-01-08  0.037012  1.129858 -0.613095  0.662517 -0.256596  0.037012
2019-01-09 -0.562650  0.395764 -0.286468 -0.998723  0.557964  0.299659
2019-01-10  0.685265  0.547729 -0.346132 -1.052215  0.804579  0.685265
2019-01-11 -1.421632 -0.684325  0.847102 -0.394123  0.175173  0.299659
2019-01-12  0.132546  1.000737 -0.957655  0.628058  0.482894  0.132546
2019-01-13  1.687166  0.142478  0.735908 -1.262935 -1.248862  1.687166
2019-01-14  0.772291 -0.264252 -0.948896  0.295195 -0.704387  0.772291
2019-01-15 -0.932837  0.577989 -1.208904  0.888597  0.821004  0.299659
2019-01-16  0.796387  0.981246 -0.168285  0.730306  0.342569  0.796387
2019-01-17  0.879396  1.403476 -0.385631 -0.713541 -0.680863  0.879396
2019-01-18  1.433495  1.462356 -0.316010  0.442342  0.917079  1.433495
2019-01-19  0.086829 -0.483861 -1.545272 -1.563401  1.280677  0.086829
2019-01-20 -0.026703  1.468383  0.493701 -0.715272 -0.190628  0.299659
2019-01-21  1.121613 -0.076973 -1.212404  1.230698 -0.415839  1.121613
2019-01-22 -0.706591 -1.913148  1.649856  0.587254  0.602772  0.299659
2019-01-23  1.661401 -1.598043 -0.985731  0.557020  0.914204  1.661401
2019-01-24 -0.767710 -1.006863  0.417234  0.734336  0.889245  0.299659
2019-01-25  0.219326  0.377491 -0.791898 -2.166056  0.134964  0.219326
2019-01-26  1.256185 -0.221268 -0.126999  1.072720  0.590782  1.256185
2019-01-27 -0.190189 -0.381672  0.241706 -0.667103 -0.061824  0.299659
2019-01-28  1.267141 -0.088902  0.594725  1.513732  0.565757  1.267141
2019-01-29  0.545309 -1.635362  0.100824 -0.719898 -0.966576  0.545309
2019-01-30  0.008506 -1.484467 -0.087392  1.349637  0.531141  0.008506
2019-01-31  0.374703 -0.720816 -0.575335 -2.583184 -1.304499  0.374703
2019-02-01  1.414207  2.333364  0.501823  1.006124  0.241484  1.414207
2019-02-02  0.755554 -1.247430 -0.939966 -0.281200 -1.063710  0.755554
2019-02-03  0.434239  2.268212  0.539058 -0.144351  1.919205  0.434239
2019-02-04 -0.942117  0.916755  0.659566 -0.343416  1.656153  0.299659
2019-02-05  0.062521 -0.375446  0.180793 -0.011549 -0.988519  0.062521
2019-02-06 -0.381810  0.278033 -0.373317 -0.462792 -0.187706  0.299659
2019-02-07 -0.105124 -0.140282  1.112371  0.966339 -1.085805  0.299659
2019-02-08  2.177779  0.431255  0.167260 -0.142036  0.679150  2.177779
2019-02-09 -0.281425 -0.036689 -1.490855  0.621211 -0.552213  0.299659
2019-02-10  0.020706 -1.725483  0.249342 -1.339386  0.918793  0.020706
2019-02-11 -0.273603 -1.125814  0.186081  0.546808 -1.481986  0.299659
2019-02-12 -0.397241  1.657093 -0.478804 -1.742314 -0.922322  0.299659
2019-02-13  0.541883 -1.111211 -1.031427 -1.153288  1.157006  0.541883
2019-02-14  0.232691  0.173339  0.496610 -1.153292  0.400405  0.232691
2019-02-15 -0.197861 -0.157348 -1.766483  1.220535 -0.136543  0.299659
2019-02-16 -0.008647 -1.637778  0.447804  0.148213  0.926302  0.299659
2019-02-17  0.570415 -0.656894 -1.722483 -0.317137  0.165141  0.570415
2019-02-18  1.336490 -0.143471 -1.058781  0.574782 -0.326431  1.336490
2019-02-19 -0.669523 -0.134644  0.679593  0.265292  2.205483  0.299659
2019-02-20  1.695557 -0.787855  0.627441  0.587332 -0.069422  1.695557
2019-02-21 -1.356159  0.043122 -0.286802  0.814177  0.845000  0.299659
2019-02-22  0.017851  1.005231  0.413347 -0.986197 -1.589328  0.017851
2019-02-23 -0.640606  0.944855 -0.495220 -0.418199 -0.156935  0.299659
2019-02-24 -1.241594  1.549985 -2.264093 -0.102376  0.184822  0.299659
2019-02-25  2.590553 -1.184675  1.541100 -1.285641 -0.009748  2.590553
2019-02-26  1.542979  1.637284 -0.110087  0.306931 -0.697036  1.542979
2019-02-27  0.573424  1.261246 -0.522436 -0.260935  0.863744  0.573424
2019-02-28 -0.778499 -0.727866 -0.415894  0.612242 -0.130658  0.299659
2019-03-01  0.609774 -0.278934 -0.811826  1.641012 -0.062515  0.609774